### PR TITLE
XGAP testing framework

### PR DESCRIPTION
**Pull request by RussWoodroofe**
Per discussion in <a href="https://github.com/gap-packages/xgap/issues/4">this issue</a>, this pull request adds a single new file under the new tst directory.  The new file defines a function which loads GAP in package ("-p") mode (including loading the XGAP GAP library) and runs a single specified command.

Main update over the version posted for discussion at the issue is commenting.  The correct commenting style to use in XGAP wasn't completely clear to me, and this may require adjustment.

### CODE REVIEW

**Comment by RussWoodroofe** [comment]
Apologies for slowness in creating the PR.  GAP Days left me with several urgent things to catch up on!

**Comment by olexandr-konovalov** [comment]
Thanks @RussWoodroofe ! We have some packages switching already to GitHub actions - e.g. https://github.com/gap-packages/example/pull/29, it would be nice if we can use the same setup, and have a .tst file which reads your .g file, runs it and should produce output as expected. I can help with adding GitHub actions here.

**Comment by RussWoodroofe** [comment]
@alex-konovalov, makes sense.  Can certainly wait until after the upcoming release.  

If I understand right, a good general structure on the GAP end would probably be to add to PackageInfo.g a "tst.testall.g" file.  The testall.g file should Read this file, and run GAP -p with a command that runs some actual tests, possibly TestDirectory(xgap/tst).

**Comment by olexandr-konovalov** [comment]
@RussWoodroofe yes, exactly

**Pull request merged**
